import { Link } from "react-router-dom"

import { LegalLayout } from "@/components/legal/LegalLayout"
import { LegalSection } from "@/components/legal/LegalSection"

export function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Service"
      updated="August 11, 2026"
      intro="These Terms govern your access to and use of Therabridge. Please read them carefully — by creating an account or using the service, you agree to be bound by them."
    >
      <LegalSection title="1. Your agreement">
        <p>
          By creating an account, signing in, or otherwise using Therabridge
          (the &ldquo;Service&rdquo;), you agree to these Terms of Service
          (the &ldquo;Terms&rdquo;), our{" "}
          <Link
            to="/privacy"
            className="text-emerald-600 underline underline-offset-2 hover:text-emerald-700 dark:text-emerald-400 dark:hover:text-emerald-300"
          >
            Privacy Policy
          </Link>
          , and our{" "}
          <Link
            to="/cookies"
            className="text-emerald-600 underline underline-offset-2 hover:text-emerald-700 dark:text-emerald-400 dark:hover:text-emerald-300"
          >
            Cookie Use
          </Link>{" "}
          policy. If you do not agree with any part of these documents, please
          do not use the Service.
        </p>
      </LegalSection>

      <LegalSection title="2. Eligibility">
        <p>
          The Service is intended for people aged 18 and older. You must be at
          least 18 years old to create an account. By registering, you confirm
          that you meet this requirement and that all information you provide
          is accurate and current.
        </p>
      </LegalSection>

      <LegalSection title="3. The services">
        <p>Therabridge provides a secure mental wellness platform including:</p>
        <ul className="list-disc space-y-1.5 pl-5">
          <li>Private direct messaging with therapists and other users</li>
          <li>Invite-only community chat rooms with moderation</li>
          <li>Therry, an AI wellness companion available around the clock</li>
          <li>Mood tracking with charts and statistics</li>
          <li>Guided wellness exercises and gamification</li>
          <li>Crisis support tools, safety plans, and escalation to your therapist</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. Not medical or emergency care">
        <p>
          Therabridge is a wellness support platform. It does not provide
          medical, psychological, or clinical diagnosis or treatment, and it is
          not an emergency service. Therry is an AI companion, not a licensed
          therapist or healthcare provider. Content generated by Therry or
          other automated features is informational only and is not a
          substitute for professional advice.
        </p>
        <p>
          If you are experiencing a medical emergency or are in immediate
          danger, please contact your local emergency services. If you are in
          crisis, use the crisis hotlines shown in the app or reach out to a
          trusted person. Crisis resources in the app are a supplement to, not
          a replacement for, emergency care.
        </p>
      </LegalSection>

      <LegalSection title="5. Your account">
        <ul className="list-disc space-y-1.5 pl-5">
          <li>You are responsible for keeping your login credentials secure.</li>
          <li>You must not share your account or allow others to access it.</li>
          <li>
            You must notify us promptly if you suspect unauthorized access to
            your account.
          </li>
          <li>
            We may suspend or disable accounts that violate these Terms or that
            we reasonably believe to be compromised.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="6. Acceptable use">
        <p>
          You agree not to use the Service to:
        </p>
        <ul className="list-disc space-y-1.5 pl-5">
          <li>Harass, abuse, threaten, or intimidate others</li>
          <li>Share content that is unlawful, defamatory, or infringing</li>
          <li>Send spam, unsolicited messages, or automated content</li>
          <li>Attempt to access accounts, systems, or data you are not authorized to access</li>
          <li>Interfere with the operation or security of the Service</li>
          <li>Scrape, crawl, or copy the Service at scale</li>
          <li>Use the Service for any unlawful purpose</li>
        </ul>
        <p>
          We may moderate, remove, or refuse content that violates these Terms
          and may restrict accounts that repeatedly violate them.
        </p>
      </LegalSection>

      <LegalSection title="7. Content you create">
        <p>
          You retain ownership of the content you create, including messages,
          mood entries, and safety plans. By posting content on the Service,
          you grant Therabridge a limited license to store, process, encrypt,
          transmit, and display that content as needed to operate the Service.
        </p>
        <p>
          You are solely responsible for the content you create and for
          ensuring it does not violate these Terms or applicable law.
        </p>
      </LegalSection>

      <LegalSection title="8. AI companion (Therry)">
        <p>
          Therry is powered by an AI model and is provided to support your
          wellbeing. AI-generated responses can be inaccurate or incomplete.
          You should not rely on Therry for professional or emergency care.
        </p>
        <p>
          To keep you safe, Therabridge may analyze your conversations for
          signs of crisis. When a crisis is detected, relevant information may
          be shared with your assigned therapist or, if you have none, with
          platform administrators, as described in our{" "}
          <Link
            to="/privacy"
            className="text-emerald-600 underline underline-offset-2 hover:text-emerald-700 dark:text-emerald-400 dark:hover:text-emerald-300"
          >
            Privacy Policy
          </Link>
          .
        </p>
      </LegalSection>

      <LegalSection title="9. Therapists & community rooms">
        <p>
          Therapists and other professionals on the platform are independent
          and are not employees or agents of Therabridge. Community rooms are
          invite-only and are moderated by their owners and moderators, who may
          approve, remove, or restrict members.
        </p>
      </LegalSection>

      <LegalSection title="10. Termination">
        <p>
          You may delete your account at any time from your settings. When you
          delete your account, we permanently delete your data as described in
          our Privacy Policy.
        </p>
        <p>
          We may suspend or terminate your access if you breach these Terms or
          if we reasonably believe continued access would harm the Service or
          other users.
        </p>
      </LegalSection>

      <LegalSection title="11. Disclaimers">
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as
          available,&rdquo; without warranties of any kind, whether express or
          implied, including fitness for a particular purpose. We do not
          guarantee that the Service will be uninterrupted, error-free, or
          completely secure, and we do not guarantee the accuracy or
          availability of AI-generated content.
        </p>
      </LegalSection>

      <LegalSection title="12. Limitation of liability">
        <p>
          To the fullest extent permitted by law, Therabridge and its operators
          shall not be liable for any indirect, incidental, special, or
          consequential damages, or for any loss of data, arising from your use
          of the Service. Nothing in these Terms limits liability that cannot
          be limited by law.
        </p>
      </LegalSection>

      <LegalSection title="13. Changes to these Terms">
        <p>
          We may update these Terms from time to time. When we make material
          changes, we will update the &ldquo;Last updated&rdquo; date above and
          post the revised Terms on this page. Your continued use of the
          Service after changes take effect means you accept the revised Terms.
        </p>
      </LegalSection>

      <LegalSection title="14. Contact us">
        <p>
          If you have questions about these Terms, please reach out through the
          in-app support channels or visit therabridge.vercel.app.
        </p>
      </LegalSection>
    </LegalLayout>
  )
}
